spring:
    sql:
        init:
            mode: always
    datasource:
        url: jdbc:postgresql://localhost:5435/postgres
        username: postgres
        password: userdb
        schema: classpath:/schema.sql
    jpa:
        hibernate:
            ddl-auto: none