spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: walletdb
    schema: classpath:/schema.sql
  jpa:
    hibernate:
      ddl-auto: none